### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ZansLord** [ImYanXiao/Elaina-MultiDevice#1]
undefined:1
Arguments:
^

SyntaxError: Unexpected token A in JSON at position 0
    at JSON.parse (<anonymous>)
    at useSingleFileAuthState (/data/data/com.termux/files/home/elaina/node_modules/@adiwajshing/baileys/lib/Utils/use-single-file-auth-state.js:36:29)
    at file:///data/data/com.termux/files/home/elaina/main.js:88:30

Node.js v18.4.0
[❗]Exited with code: null

**Comment by ImYanXiao** [comment]
Now try again breh
