### ISSUE TITLE
Tiktok.js error

### ISSUE THREAD

**Issue by Denz4323** [ImYanXiao/Elaina-MultiDevice#39]
```TypeError: Cannot read properties of undefined (reading 'includes')
    at tiktokdl (file:///home/runner/apani/node_modules/@bochilteam/scraper/lib/esm/social-media/tiktok.js:39:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/runner/apani/plugins/downloader-tiktok.js:10:27
    at async Object.handler (file:///home/runner/apani/plugins/downloader-tiktok.js:8:58)
    at async Object.handler (file:///home/runner/apani/handler.js?update=1674184910940:572:21)```

**Comment by ImYanXiao** [comment]
😔☝

**Comment by Denz4323** [comment]
Dah
